# Generated by Django 5.2 on 2025-05-02 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=254)),
                ('nro_telefono', models.IntegerField()),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('nro_documento', models.IntegerField()),
                ('genero', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('estado_civil', models.CharField(max_length=50)),
                ('campus_sede', models.CharField(max_length=100)),
                ('facultad', models.CharField(max_length=100)),
                ('carrera', models.CharField(max_length=100)),
                ('ano_ingreso', models.IntegerField()),
                ('ano_egreso', models.IntegerField()),
                ('ano_primer_empleo', models.IntegerField()),
                ('ano_primer_empleo_carrera', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=1)),
            ],
        ),
    ]
