# Generated by Django 5.2 on 2025-05-03 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampusSede',
            fields=[
                ('id_campus_sede', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id_carrera', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id_facultad', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta_borrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_documento', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=255)),
                ('nro_telefono', models.CharField(max_length=50)),
                ('nombres', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('genero', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=255)),
                ('estado_civil', models.CharField(max_length=50)),
                ('facultad', models.CharField(max_length=255)),
                ('carrera', models.CharField(max_length=255)),
                ('campus_sede', models.CharField(max_length=255)),
                ('ano_ingreso', models.IntegerField()),
                ('ano_egreso', models.IntegerField()),
                ('ano_primer_empleo', models.IntegerField()),
                ('ano_primer_empleo_carrera', models.IntegerField()),
                ('estado', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta_oficial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=254)),
                ('nro_telefono', models.CharField(max_length=50)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('nro_documento', models.CharField(max_length=20)),
                ('genero', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('estado_civil', models.CharField(max_length=50)),
                ('ano_ingreso', models.IntegerField()),
                ('ano_egreso', models.IntegerField()),
                ('ano_primer_empleo', models.IntegerField()),
                ('ano_primer_empleo_carrera', models.IntegerField()),
                ('campus_sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estadistica_egresados.campussede')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estadistica_egresados.carrera')),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estadistica_egresados.facultad')),
            ],
        ),
    ]
