# Generated by Django 5.2 on 2025-05-17 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampusSede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta_borrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_encuesta', models.DateTimeField(blank=True, null=True)),
                ('fecha_hora_encuesta_anterior', models.DateTimeField(blank=True, null=True)),
                ('nro_registro', models.IntegerField(blank=True, null=True, unique=True)),
                ('correo', models.CharField(max_length=255)),
                ('nro_telefono', models.CharField(max_length=50)),
                ('nombres', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('nro_documento', models.CharField(max_length=20)),
                ('genero', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=255)),
                ('estado_civil', models.CharField(max_length=50)),
                ('campus_sede', models.CharField(max_length=255)),
                ('facultad', models.CharField(max_length=255)),
                ('carrera', models.CharField(max_length=255)),
                ('ano_ingreso', models.IntegerField()),
                ('ano_egreso', models.IntegerField()),
                ('ind_trabaja', models.CharField(max_length=2)),
                ('ano_primer_empleo', models.IntegerField(blank=True, null=True)),
                ('ind_empleo_relacionado_carrera', models.CharField(blank=True, max_length=2, null=True)),
                ('ind_plan_curricular_optimo', models.CharField(blank=True, max_length=2, null=True)),
                ('valoracion_aprendizaje_docente', models.IntegerField(blank=True, null=True)),
                ('ind_materias_utiles', models.CharField(blank=True, max_length=2, null=True)),
                ('valoracion_impacto_formacion_academica_laboral', models.IntegerField(blank=True, null=True)),
                ('opcional_aprendizajes_no_curriculares', models.TextField(blank=True, null=True)),
                ('ano_primer_empleo_carrera', models.IntegerField(blank=True, null=True)),
                ('ind_oportunidad_desarrollo_profesional', models.CharField(blank=True, max_length=2, null=True)),
                ('valoracion_estudios_trayectoria_profesional', models.IntegerField(blank=True, null=True)),
                ('opcional_influencia_en_trayectoria', models.TextField(blank=True, null=True)),
                ('ind_participa_actividad_egresado', models.CharField(max_length=2)),
                ('ind_interes_participar_actividad_egresado', models.CharField(max_length=2)),
                ('ind_interes_posgrado', models.CharField(max_length=2)),
                ('tipo_posgrado', models.CharField(max_length=255)),
                ('opcional_area_posgrado', models.TextField(blank=True, null=True)),
                ('opcional_estrategia_convocatoria', models.TextField(blank=True, null=True)),
                ('opcional_contacto_carrera', models.TextField(blank=True, null=True)),
                ('hash_valor', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('estado', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPosgrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta_oficial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_encuesta', models.DateTimeField(blank=True, null=True)),
                ('correo', models.EmailField(max_length=254)),
                ('nro_telefono', models.CharField(max_length=50)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('nro_documento', models.CharField(max_length=20)),
                ('ciudad', models.CharField(max_length=255)),
                ('ano_ingreso', models.IntegerField()),
                ('ano_egreso', models.IntegerField()),
                ('ind_trabaja', models.CharField(max_length=2)),
                ('ano_primer_empleo', models.IntegerField(blank=True, null=True)),
                ('ind_empleo_relacionado_carrera', models.CharField(blank=True, max_length=2, null=True)),
                ('ind_plan_curricular_optimo', models.CharField(blank=True, max_length=2, null=True)),
                ('valoracion_aprendizaje_docente', models.IntegerField(blank=True, null=True)),
                ('ind_materias_utiles', models.CharField(blank=True, max_length=2, null=True)),
                ('valoracion_impacto_formacion_academica_laboral', models.IntegerField(blank=True, null=True)),
                ('opcional_aprendizajes_no_curriculares', models.TextField(blank=True, null=True)),
                ('ano_primer_empleo_carrera', models.IntegerField(blank=True, null=True)),
                ('ind_oportunidad_desarrollo_profesional', models.CharField(blank=True, max_length=2, null=True)),
                ('valoracion_estudios_trayectoria_profesional', models.IntegerField(blank=True, null=True)),
                ('opcional_influencia_en_trayectoria', models.TextField(blank=True, null=True)),
                ('ind_participa_actividad_egresado', models.CharField(max_length=2)),
                ('ind_interes_participar_actividad_egresado', models.CharField(max_length=2)),
                ('ind_interes_posgrado', models.CharField(max_length=2)),
                ('opcional_area_posgrado', models.TextField(blank=True, null=True)),
                ('opcional_estrategia_convocatoria', models.TextField(blank=True, null=True)),
                ('opcional_contacto_carrera', models.TextField(blank=True, null=True)),
                ('campus_sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estadistica_egresados.campussede')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estadistica_egresados.carrera')),
                ('estado_civil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estadistica_egresados.estadocivil')),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estadistica_egresados.facultad')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estadistica_egresados.genero')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estadistica_egresados.pais')),
                ('tipo_posgrado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estadistica_egresados.tipoposgrado')),
            ],
        ),
    ]
