# Generated by Django 5.2 on 2025-05-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadistica_egresados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta_borrador',
            name='ind_materias_utiles',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='respuesta_borrador',
            name='opcional_aprendizajes_no_curriculares',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='respuesta_borrador',
            name='valoracion_impacto_formacion_academica_laboral',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='respuesta_oficial',
            name='ind_materias_utiles',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='respuesta_oficial',
            name='opcional_aprendizajes_no_curriculares',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='respuesta_oficial',
            name='valoracion_impacto_formacion_academica_laboral',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='respuesta_borrador',
            name='ind_empleo_relacionado_carrera',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='respuesta_borrador',
            name='ind_plan_curricular_optimo',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='respuesta_borrador',
            name='valoracion_aprendizaje_docente',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='respuesta_oficial',
            name='ind_empleo_relacionado_carrera',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='respuesta_oficial',
            name='ind_plan_curricular_optimo',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='respuesta_oficial',
            name='valoracion_aprendizaje_docente',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
