# Generated by Django 5.2 on 2025-05-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadistica_egresados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta_borrador',
            name='nro_registro',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
