# Generated by Django 5.2 on 2025-05-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadistica_egresados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta_borrador',
            name='opcional_area_posgrado',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='respuesta_borrador',
            name='opcional_contacto_carrera',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='respuesta_borrador',
            name='opcional_estrategia_convocatoria',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='respuesta_oficial',
            name='opcional_area_posgrado',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='respuesta_oficial',
            name='opcional_contacto_carrera',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='respuesta_oficial',
            name='opcional_estrategia_convocatoria',
            field=models.TextField(blank=True, null=True),
        ),
    ]
