# Generated by Django 5.2 on 2025-05-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadistica_egresados', '0002_respuesta_borrador_nro_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta_borrador',
            name='fecha_hora_encuesta',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
