# Generated by Django 5.2 on 2025-05-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadistica_egresados', '0003_respuesta_borrador_fecha_hora_encuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta_borrador',
            name='fecha_hora_encuesta_anterior',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='respuesta_oficial',
            name='fecha_hora_encuesta',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
