# Generated by Django 5.2 on 2025-05-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadistica_egresados', '0004_respuesta_borrador_fecha_hora_encuesta_anterior_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta_borrador',
            name='hash_valor',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
