# Generated by Django 5.2 on 2025-05-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadistica_egresados', '0005_respuesta_borrador_hash_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta_borrador',
            name='ano_primer_empleo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='respuesta_borrador',
            name='ano_primer_empleo_carrera',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='respuesta_oficial',
            name='ano_primer_empleo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='respuesta_oficial',
            name='ano_primer_empleo_carrera',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
